
package MenuPrincipal;

import Mantenimientos.Catalogoframe;
import Mantenimientos.UsuarioFrame;
import Mantenimientos.Documentoframe;

public class MenuPrincipal extends javax.swing.JFrame {

 
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bg = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MantenimientoMenu3 = new javax.swing.JMenu();
        UsuariosMenuItem2 = new javax.swing.JMenuItem();
        CatalogoMenuItem3 = new javax.swing.JMenuItem();
        DocumentosMenuItem4 = new javax.swing.JMenuItem();
        ConsultasMenu1 = new javax.swing.JMenu();
        ProcesosMenu2 = new javax.swing.JMenu();
        MovimientoMenu5 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setLocationByPlatform(true);

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(24, 113, 203));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENIDO");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(235, 235, 235))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jLabel1)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        bg.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        MantenimientoMenu3.setText("Mantenimiento");

        UsuariosMenuItem2.setText("Usuarios");
        UsuariosMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuariosMenuItem2ActionPerformed(evt);
            }
        });
        MantenimientoMenu3.add(UsuariosMenuItem2);

        CatalogoMenuItem3.setText("Catalogo de cuenta");
        CatalogoMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatalogoMenuItem3ActionPerformed(evt);
            }
        });
        MantenimientoMenu3.add(CatalogoMenuItem3);

        DocumentosMenuItem4.setText("Documentos");
        DocumentosMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentosMenuItem4ActionPerformed(evt);
            }
        });
        MantenimientoMenu3.add(DocumentosMenuItem4);

        jMenuBar1.add(MantenimientoMenu3);

        ConsultasMenu1.setText("Consultas");
        jMenuBar1.add(ConsultasMenu1);

        ProcesosMenu2.setText("Procesos");
        jMenuBar1.add(ProcesosMenu2);

        MovimientoMenu5.setText("Movimientos");
        jMenuBar1.add(MovimientoMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariosMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosMenuItem2ActionPerformed
       UsuarioFrame usuarioForm = new UsuarioFrame(); 
       usuarioForm.setVisible(true); 
    }//GEN-LAST:event_UsuariosMenuItem2ActionPerformed

    private void CatalogoMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatalogoMenuItem3ActionPerformed
        Catalogoframe CatalogoForm = new Catalogoframe();
        CatalogoForm.setVisible(true);
    }//GEN-LAST:event_CatalogoMenuItem3ActionPerformed

    private void DocumentosMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentosMenuItem4ActionPerformed
        Documentoframe documentForm =new Documentoframe(); 
        documentForm.setVisible(true);
    }//GEN-LAST:event_DocumentosMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CatalogoMenuItem3;
    private javax.swing.JMenu ConsultasMenu1;
    private javax.swing.JMenuItem DocumentosMenuItem4;
    private javax.swing.JMenu MantenimientoMenu3;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JMenu MovimientoMenu5;
    private javax.swing.JMenu ProcesosMenu2;
    private javax.swing.JMenuItem UsuariosMenuItem2;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
